-- =====================================================================
-- V1 - Baseline schema for FreshLink.
--
-- Verified against PostgreSQL: this is a cleaned-up pg_dump of the schema
-- Hibernate actually creates, so `ddl-auto=validate` passes against it.
--
-- Names are snake_case because Spring Boot applies
-- CamelCaseToUnderscoresNamingStrategy - businessRegNo becomes
-- business_reg_no, DailySupply becomes daily_supply. Do not "tidy" these
-- back to camelCase, and do not quote them: either change stops validation
-- from matching.
--
-- Foreign keys are given readable names instead of Hibernate's generated
-- hashes (validation does not check FK names), and FK columns are indexed
-- because PostgreSQL does not do that for you.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Users. JOINED inheritance: one row in user_table per account, plus one
-- in the matching subtype table sharing the same id.
-- ---------------------------------------------------------------------
create table user_table (
    id             bigint generated by default as identity primary key,
    user_type      varchar(31) not null,
    name           varchar(255) not null,
    email          varchar(255) not null unique,
    phone          varchar(255) not null,
    active         boolean not null,
    role           varchar(255) not null,
    password_hash  varchar(255),
    email_verified boolean,
    -- Non-null means soft-deleted: the row survives so orders and ratings
    -- keep their references and trade history stays intact.
    deleted_at     timestamp(6),
    constraint user_table_user_type_check check (user_type in ('ADMIN', 'CAFE', 'SUPPLIER')),
    constraint user_table_role_check check (role in ('SUPPLIER', 'CAFE', 'ADMIN'))
);

create table admin_table (
    id bigint not null primary key
);

create table cafe (
    id              bigint not null primary key,
    address         varchar(255) not null,
    business_reg_no varchar(255)
);

create table supplier (
    id             bigint not null primary key,
    location       varchar(255) not null,
    license_number varchar(255),
    average_rating double precision,
    rating_count   integer
);

-- ---------------------------------------------------------------------
-- Catalogue and inventory
-- ---------------------------------------------------------------------
create table fish_types (
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null unique,
    season_start date,
    season_end   date
);

create table fish (
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null,
    price_per_kg numeric(38, 2) not null,
    available_kg double precision not null,
    reserved_kg  double precision not null,
    -- Guards against two concurrent orders reserving the same stock.
    version      bigint,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    fish_type_id bigint not null,
    supplier_id  bigint not null
);

create table daily_supply (
    id              bigint generated by default as identity primary key,
    quantity        double precision,
    catch_date_time timestamp(6),
    freshness_score double precision,
    status          varchar(255),
    fish_type_id    bigint,
    supplier_id     bigint,
    constraint daily_supply_status_check
        check (status in ('AVAILABLE', 'PARTIAL', 'EXHAUSTED', 'RESERVED'))
);

-- ---------------------------------------------------------------------
-- Demand and matching
-- ---------------------------------------------------------------------
create table demand_request (
    id                 bigint generated by default as identity primary key,
    requested_quantity double precision,
    required_date      date,
    week_start_date    date,
    status             varchar(255),
    cafe_id            bigint,
    fish_type_id       bigint,
    constraint demand_request_status_check
        check (status in ('OPEN', 'PARTIALLY_MATCHED', 'FULLY_MATCHED', 'FULFILLED', 'CANCELLED'))
);

create table supply_match (
    id                 bigint generated by default as identity primary key,
    confirmed_quantity double precision,
    status             varchar(255),
    daily_supply_id    bigint,
    demand_request_id  bigint,
    constraint supply_match_status_check
        check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED'))
);

-- ---------------------------------------------------------------------
-- Orders and fulfilment
-- ---------------------------------------------------------------------
create table orders (
    id          bigint generated by default as identity primary key,
    status      varchar(255) not null,
    created_at  timestamp(6) not null,
    cafe_id     bigint not null,
    supplier_id bigint not null,
    constraint orders_status_check
        check (status in ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'DELIVERING', 'COMPLETED'))
);

create table order_items (
    id          bigint generated by default as identity primary key,
    quantity_kg double precision not null,
    price_per_kg numeric(38, 2) not null,
    fish_id     bigint not null,
    order_id    bigint not null
);

create table delivery (
    delivery_id   bigint generated by default as identity primary key,
    delivery_date timestamp(6),
    status        varchar(255),
    order_id      bigint unique,
    constraint delivery_status_check check (status in ('SCHEDULED', 'DELIVERED'))
);

create table rating (
    id          bigint generated by default as identity primary key,
    score       integer,
    comment     varchar(255),
    created_at  timestamp(6),
    -- One rating per order.
    order_id    bigint unique,
    cafe_id     bigint,
    supplier_id bigint,
    constraint rating_score_check check (score >= 1 and score <= 5)
);

-- ---------------------------------------------------------------------
-- Auth support
-- ---------------------------------------------------------------------
create table refresh_token (
    id          bigint generated by default as identity primary key,
    token       varchar(255),
    email       varchar(255),
    expiry_time timestamp(6)
);

create table otp_verification (
    id         bigint generated by default as identity primary key,
    email      varchar(255),
    otp        varchar(255),
    attempts   integer not null,
    expires_at timestamp(6),
    verified   boolean not null
);

-- =====================================================================
-- Foreign keys
-- =====================================================================
alter table admin_table add constraint fk_admin_user
    foreign key (id) references user_table (id);
alter table cafe add constraint fk_cafe_user
    foreign key (id) references user_table (id);
alter table supplier add constraint fk_supplier_user
    foreign key (id) references user_table (id);

alter table fish add constraint fk_fish_fish_type
    foreign key (fish_type_id) references fish_types (id);
alter table fish add constraint fk_fish_supplier
    foreign key (supplier_id) references supplier (id);

alter table daily_supply add constraint fk_daily_supply_fish_type
    foreign key (fish_type_id) references fish_types (id);
alter table daily_supply add constraint fk_daily_supply_supplier
    foreign key (supplier_id) references supplier (id);

alter table demand_request add constraint fk_demand_request_cafe
    foreign key (cafe_id) references cafe (id);
alter table demand_request add constraint fk_demand_request_fish_type
    foreign key (fish_type_id) references fish_types (id);

alter table supply_match add constraint fk_supply_match_daily_supply
    foreign key (daily_supply_id) references daily_supply (id);
alter table supply_match add constraint fk_supply_match_demand_request
    foreign key (demand_request_id) references demand_request (id);

alter table orders add constraint fk_orders_cafe
    foreign key (cafe_id) references cafe (id);
alter table orders add constraint fk_orders_supplier
    foreign key (supplier_id) references supplier (id);

alter table order_items add constraint fk_order_items_fish
    foreign key (fish_id) references fish (id);
alter table order_items add constraint fk_order_items_order
    foreign key (order_id) references orders (id);

alter table delivery add constraint fk_delivery_order
    foreign key (order_id) references orders (id);

alter table rating add constraint fk_rating_order
    foreign key (order_id) references orders (id);
alter table rating add constraint fk_rating_cafe
    foreign key (cafe_id) references cafe (id);
alter table rating add constraint fk_rating_supplier
    foreign key (supplier_id) references supplier (id);

-- =====================================================================
-- Indexes
--
-- PostgreSQL indexes primary keys and unique columns automatically but
-- not foreign keys. Each of these backs a query the app actually runs.
-- =====================================================================
create index idx_fish_supplier on fish (supplier_id);
create index idx_fish_fish_type on fish (fish_type_id);

create index idx_daily_supply_supplier on daily_supply (supplier_id);
create index idx_daily_supply_fish_type on daily_supply (fish_type_id);
create index idx_daily_supply_status on daily_supply (status);

create index idx_demand_request_cafe on demand_request (cafe_id);
create index idx_demand_request_fish_type on demand_request (fish_type_id);
create index idx_demand_request_status on demand_request (status);

create index idx_supply_match_daily_supply on supply_match (daily_supply_id);
create index idx_supply_match_demand_request on supply_match (demand_request_id);
create index idx_supply_match_status on supply_match (status);

create index idx_orders_cafe on orders (cafe_id);
create index idx_orders_supplier on orders (supplier_id);
create index idx_orders_status on orders (status);
create index idx_orders_created_at on orders (created_at);

create index idx_order_items_order on order_items (order_id);
create index idx_order_items_fish on order_items (fish_id);

create index idx_rating_supplier on rating (supplier_id);
create index idx_rating_cafe on rating (cafe_id);

-- Refresh tokens are looked up by value on every refresh and purged by
-- email on logout; OTPs are looked up by email, newest first.
create index idx_refresh_token_token on refresh_token (token);
create index idx_refresh_token_email on refresh_token (email);
create index idx_otp_verification_email on otp_verification (email);

-- The soft-delete filter appears in every admin listing and market query.
create index idx_user_table_deleted_at on user_table (deleted_at);
