-- =====================================================================
-- V6 - Keep the price a listing has charged over time.
--
-- fish.price_per_kg is overwritten on every update, so the previous value
-- was discarded. That is some of the most commercially useful data on the
-- platform: a cafe judging whether today's offer is fair has nothing to
-- compare against, and seasonal movement is invisible.
--
-- Append-only; rows are written when a listing is created and whenever its
-- price actually changes.
-- =====================================================================

create table fish_price_history (
    id           bigint generated by default as identity primary key,
    fish_id      bigint not null,
    price_per_kg numeric(38, 2) not null,
    recorded_at  timestamp(6)
);

alter table fish_price_history
    add constraint fk_fish_price_history_fish
    foreign key (fish_id) references fish (id);

-- Every read is "this listing's prices, newest first".
create index idx_fish_price_history_fish_recorded
    on fish_price_history (fish_id, recorded_at desc);

-- Backfill the current price so existing listings start with a baseline
-- rather than an empty history.
insert into fish_price_history (fish_id, price_per_kg, recorded_at)
select id, price_per_kg, coalesce(created_at, now()) from fish;
