-- =====================================================================
-- V7 - Group deliveries into driver routes.
--
-- Deliveries were only manageable one at a time, which does not reflect
-- how a supplier works: a van leaves with several cafes on board and the
-- driver details had to be retyped for every stop, with nothing tying the
-- trip together.
-- =====================================================================

create table delivery_route (
    id           bigint generated by default as identity primary key,
    supplier_id  bigint not null,
    route_date   date,
    driver_name  varchar(255),
    driver_phone varchar(255),
    status       varchar(255),
    notes        varchar(500),
    created_at   timestamp(6),
    constraint delivery_route_status_check
        check (status in ('PLANNED', 'DISPATCHED', 'COMPLETED', 'CANCELLED'))
);

alter table delivery_route
    add constraint fk_delivery_route_supplier
    foreign key (supplier_id) references supplier (id);

-- Nullable: a delivery does not have to belong to a route, and removing a
-- route only unassigns its stops rather than deleting them.
alter table delivery add column route_id bigint;

alter table delivery
    add constraint fk_delivery_route
    foreign key (route_id) references delivery_route (id);

create index idx_delivery_route_supplier_date on delivery_route (supplier_id, route_date);
create index idx_delivery_route_id on delivery (route_id);
